name: Turborepo CI

on: workflow_call

concurrency:
  group: turborepo-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  audit:
    name: pnpm audit
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Run audit
        run: pnpm audit --prod --audit-level high

  build:
    name: Lint, Build, and Test
    needs: audit
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Manypkg Check
        run: pnpm manypkg check
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - name: Lint
        run: pnpm turbo lint
      - name: Install wasm-pack for mbf package
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Build
        run: pnpm turbo build
      - name: Test
        run: pnpm turbo test
      # Pack wallet extension and upload it as an artifact for easy developer use:
      - name: Wallet Extension Has Changes?
        id: wallet-diff
        continue-on-error: true
        run: pnpm dlx turbo-ignore iota-wallet
      - name: Wallet Extension Preview Package
        if: steps.wallet-diff.outcome == 'failure'
        run: pnpm --filter iota-wallet pack:zip
      - uses: actions/upload-artifact@v4
        if: steps.wallet-diff.outcome == 'failure'
        with:
          name: wallet-extension
          path: apps/wallet/web-ext-artifacts/*
          if-no-files-found: error
          retention-days: 7
